"""empty message

Revision ID: 7aa70ad44719
Revises: None
Create Date: 2017-01-14 18:50:52.756134

"""

# revision identifiers, used by Alembic.
revision = '7aa70ad44719'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unigrams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word1', sa.String(), nullable=False),
    sa.Column('word2', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unigrams_word1'), 'unigrams', ['word1'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unigrams_word1'), table_name='unigrams')
    op.drop_table('unigrams')
    # ### end Alembic commands ###
